# Introduction

In [50]:
#pandas -open source library to manipulate high performance data in python
#Wes McKinney in 2008 and is used for data analysis
#restructuring, cleaning, merging - necessary for data analysis

#source of data - 5steps
#load, manipulate, prepare, model, and analyze.

#key features
#DataFrame quick & effective,standard & custom indexing
#reshaping and turning of the informational indexes
#aggregations and transformations, group by data
#align the data and integrate the data missing
#Time Series functionality
#various formats-matrix,heterogeneous tabular data, and time series
#multiple operations-subsetting, slicing, filtering, groupBy, reordering, and reshaping
#using  SciPy, and scikit-learn.


#benefits
#representation of data
#clear code

## Series

In [51]:
#1d array,index-row labels
#multiple cols cant be included
#data can be any list, dictionary, or scalar value
import pandas as pd
import numpy as np
a=np.array(['s','n','e','h','a'])
b=pd.Series(a)
print(a)
print(b)

['s' 'n' 'e' 'h' 'a']
0    s
1    n
2    e
3    h
4    a
dtype: object

## DataFrame

In [52]:
#two-layered exhibit with named tomahawks (lines and segments)
#two distinct indexes-row index and column index
#heterogeneous sorts like int, bool
#"columns" for rows and "index" for columns
import pandas as pd
a=['sneha','suresh']
d=pd.DataFrame(a)
print(d)

        0
0   sneha
1  suresh

# Series

In [53]:
#empty 
a=pd.Series()
print(a)

Series([], dtype: object)

In [54]:
info = np.array(['P','a','n','d','a','s'])  
a = pd.Series(info)  
print(a)

0    P
1    a
2    n
3    d
4    a
5    s
dtype: object

In [55]:
#dict
info = {'x' : 0., 'y' : 1., 'z' : 2.}  
a = pd.Series(info)  
print (a)

x    0.0
y    1.0
z    2.0
dtype: float64

In [56]:
x = pd.Series(4, index=[0, 1, 2, 3])  
print (x)

0    4
1    4
2    4
3    4
dtype: int64

In [57]:
x=pd.Series(data=[2,4,6,8])   
y=pd.Series(data=[11.2,18.6,22.5], index=['a','b','c'])  
print(x[0])
print(x.index,y.index)
print(x.values,y.values)
print(x.dtype,y.dtype)
print(x.shape,y.shape)
print(x.ndim,y.ndim)
print(x.size, y.size)   
print(x.nbytes, y.nbytes)  
print(x.empty)
#hasnans -nan values
a=pd.Series(data=[1,2,3,np.nan]) 
print(a.hasnans)
print(len(x),len(y))   
print(x.count( ),y.count( ))

2
RangeIndex(start=0, stop=4, step=1) Index(['a', 'b', 'c'], dtype='object')
[2 4 6 8] [11.2 18.6 22.5]
int64 float64
(4,) (3,)
1 1
4 3
32 24
False
True
4 3
4 3

**Series.map**

In [58]:
#map the values from two series that have a common column
#last col of 1st Series should be same as index col of 2nd Series ,value sshould be unique
#syn:Series.map(arg, na_action=None)
#arg: function, dict, or Series
#na_action: {None, 'ignore'}, Default value None,ignore returns null values
a=pd.Series(['java','c','c++',np.nan])
a.map({'java':'core'})

0    core
1     NaN
2     NaN
3     NaN
dtype: object

In [59]:
a.map("i like {}".format)

0    i like java
1       i like c
2     i like c++
3     i like nan
dtype: object

In [60]:
a.map("i like {}".format,na_action="ignore")

0    i like java
1       i like c
2     i like c++
3            NaN
dtype: object

**Series.std**

In [61]:
#syn:Series.std(axis=None, skipna=None, level=None, ddof=1, numeric_only=None, **kwargs)  
#skipna - exclude null values,if present entire row or col NA
#level - count along a particular level,collapse into scalar if axis is MultiIndex
#ddof - delta degrees of freedom
print(np.std([4,7,2,1,6,3]))

2.1147629234082532

In [62]:
 info = {  
    'Name':['Parker','Smith','John','William'],  
   'sub1_Marks':[52,38,42,37],  
   'sub2_Marks':[41,35,29,36]}   
data = pd.DataFrame(info)  
print(data)  
a={'sub1_Marks':[52,38,42,37],  
   'sub2_Marks':[41,35,29,36]} 
df = pd.DataFrame(a)
df.std()

      Name  sub1_Marks  sub2_Marks
0   Parker          52          41
1    Smith          38          35
2     John          42          29
3  William          37          36

sub1_Marks    6.849574
sub2_Marks    4.924429
dtype: float64

**Series.to_frame()**

In [63]:
#series object to the DataFrame
#syn:Series.to_frame(name=None)
a=pd.Series(['a','b','c'],name="val")
a.to_frame()

  val
0   a
1   b
2   c

In [76]:
emp = ['Parker', 'John', 'Smith', 'William']   
id = [102, 107, 109, 114]     
e = pd.Series(emp)   
i = pd.Series(id)  
frame = { 'Emp': e, 'ID': i}   
result = pd.DataFrame(frame)     
print(result)

       Emp   ID
0   Parker  102
1     John  107
2    Smith  109
3  William  114

**Series.unique()**

In [74]:
#unique elements
#syn:pandas.unique(values)
print(pd.unique(pd.Series([2, 1, 3, 3])) ) 
pd.unique(pd.Series([pd.Timestamp('20160101'),  
pd.Timestamp('20160101')]))

[2 1 3]

array(['2016-01-01T00:00:00.000000000'], dtype='datetime64[ns]')

**Series.value_consts()**

In [78]:
#ounts of unique values
#syn:Series.value_counts(normalize=False, sort=True, ascending=False, bins=None, dropna=True)  
index = pd.Index([2, 1, 1, np.nan, 3])  
index.value_counts()

1.0    2
2.0    1
3.0    1
Name: count, dtype: int64

In [79]:
index = pd.Index([2, 1, 1, np.nan, 3])  
a = pd.Series([2, 1, 1, np.nan, 3])  
a.value_counts(normalize=True)

1.0    0.50
2.0    0.25
3.0    0.25
Name: proportion, dtype: float64

In [80]:
index = pd.Index([1, 3, 2, 2, 1, np.nan])  
index.value_counts()  
a = pd.Series([1, 3, 2, 2, 1, np.nan])  
a.value_counts(dropna=False)

1.0    2
2.0    2
3.0    1
NaN    1
Name: count, dtype: int64

In [81]:
index = pd.Index([1, 3, 2, 2, 1, np.nan])  
index.value_counts()  
a = pd.Series([1, 3, 2, 2, 1, np.nan])  
a.value_counts(bins=2)

(0.997, 2.0]    4
(2.0, 3.0]      1
Name: count, dtype: int64

# Data Frame

In [2]:
#widely used data structure with 2-D array with labeled(rows & cols)
#col can be heterogenous type like int,bool
#columns in case of cols ,index in case of rows

#index:default np.arrange(n) - row labels if no index passed
#columns:default np.arrange(n) - shows true if no index passed
import pandas as pd
d=pd.DataFrame()
print(d)

Empty DataFrame
Columns: []
Index: []

**from list**

In [4]:
a=[1,"ene",32.3]
d=pd.DataFrame(a)
print(d)

      0
0     1
1   ene
2  32.3

**from Dict of ndarrays/ Lists**

In [7]:
a={'id':[1,2,3],'Dept':['cse','ece','mech']}
d=pd.DataFrame(a)
print(d)

   id  Dept
0   1   cse
1   2   ece
2   3  mech

**from Dict of Series**

In [8]:
a={'one':pd.Series([1,2,3,4,5,6],index=['a','b','c','d','e','f']),'two':pd.Series([1,2,3],index=['a','b','c'])}
d=pd.DataFrame(a)
print(d)

   one  two
a    1  1.0
b    2  2.0
c    3  3.0
d    4  NaN
e    5  NaN
f    6  NaN

In [11]:
#column selection
print(d['one'])

a    1
b    2
c    3
d    4
e    5
f    6
Name: one, dtype: int64

In [10]:
print(d['two'])

a    1.0
b    2.0
c    3.0
d    NaN
e    NaN
f    NaN
Name: two, dtype: float64

**column addition**

In [12]:
d['three']=pd.Series([20,30,40],index=['a','b','c'])
print(d)

   one  two  three
a    1  1.0   20.0
b    2  2.0   30.0
c    3  3.0   40.0
d    4  NaN    NaN
e    5  NaN    NaN
f    6  NaN    NaN

**column deletion**

In [13]:
del d['one']
print(d)

   two  three
a  1.0   20.0
b  2.0   30.0
c  3.0   40.0
d  NaN    NaN
e  NaN    NaN
f  NaN    NaN

**selection of row by loc**

In [15]:
#consists two Series with its respective ind
print(d.loc['b'])

two       2.0
three    30.0
Name: b, dtype: float64

**selection of row by iloc**

In [18]:
#integer location to an iloc
print(d.iloc[2])

two       3.0
three    40.0
Name: c, dtype: float64

**slice rows**

In [19]:
print(d[2:5])

   two  three
c  3.0   40.0
d  NaN    NaN
e  NaN    NaN

**Addition of rows**

In [26]:
import pandas as pd
d = pd.DataFrame([[7, 8], [9, 10]], columns = ['x','y'])  
d2 = pd.DataFrame([[11, 12], [13, 14]], columns = ['x','y'])  
#d = d.append(d2)  
print(d) 
#to drop
d=d.drop(0)

   x   y
0  7   8
1  9  10

**DataFrame.append**

In [31]:
#add the rows of other dataframe to the end of other
#syn:DataFrame.append(other, ignore_index=False, verify_integrity=False, sort=None)
#ignore_index : not use index labels
#verify_integrity:if true ValueError on creating an index with duplicates
d1 = pd.DataFrame({"x":[25,15,12,19],   
                    "y":[47, 24, 17, 29]})
d2 = pd.DataFrame({"x":[25, 15, 12],   
                    "y":[47, 24, 17],    
                    "z":[38, 12, 45]}) 
d1.append(d2,ignore_index=True)

#Error occurs

AttributeError: 'DataFrame' object has no attribute 'append'

**DatFrame.apply**

In [34]:
#pass a function and apply it to every single value of the Pandas series
#syn:DataFrame.apply(func, axis=0, broadcast=None, raw=False, reduce=None, result_type=None, args=(), **kwds) 
#axis : default 0, 0-index each col,1-col each row
#boardcast optional parameter
#raw:bool default false-passes each row or column as a Series to the function,
#if true-ndarray objects
import numpy as np
a=pd.DataFrame([[1,2]]*3,columns=['a','b'])
print(a)
print(a.apply(np.sqrt))
print(a.apply(np.sum,axis=0))

   a  b
0  1  2
1  1  2
2  1  2
     a         b
0  1.0  1.414214
1  1.0  1.414214
2  1.0  1.414214
a    3
b    6
dtype: int64

**DataFrame.aggregate**

In [35]:
#aggregation to one or more column-sum,min,max
#syn:DataFrame.aggregate(func, axis=0, *args, **kwargs)
#**kwargs:keyword argument passed to function
#scalar=Series.agg single function
#Series=DataFrame.agg single function
#DataFrame=DataFrame.agg several functions
info=pd.DataFrame([[1,5,7],[10,12,15],[18,21,24],[np.nan,np.nan,np.nan]],columns=['X','Y','Z'])  
info.agg(['sum','min'])

        X     Y     Z
sum  29.0  38.0  46.0
min   1.0   5.0   7.0

 **DataFrame.assign**

In [37]:
#adding a new column into a DataFrame
#syn:DataFrame.assign(**kwargs)  
a=pd.DataFrame()
a['id']=[1,2,3]
print(a)
a.assign(name=['sne','ha','sri'])

   id
0   1
1   2
2   3

   id name
0   1  sne
1   2   ha
2   3  sri

In [47]:
a=pd.DataFrame({'celsius':[15,33]},index=["rgt","tpt"])
print(a)
a.assign(farenheit=lambda x:x.celsius*7/2+24)
a.assign(farenheit=lambda x:x.celsius*7/2+24,kelvin=lambda x:(x['farenheit']+342.27)*6/24)

     celsius
rgt       15
tpt       33

     celsius  farenheit    kelvin
rgt       15       76.5  104.6925
tpt       33      139.5  120.4425

**DataFrame.astype**

In [9]:
#syn:DataFrame.astype(dtype, copy=True, errors='raise', **kwargs)  
#casting the pandas object to a specified dtype.astype()
import pandas as pd
a={'col1':[1,2],'col2':[3, 4]} 
d=pd.DataFrame(data=a)
print(d.dtypes)
d.astype('int32').dtypes
x = pd.Series([1, 2], dtype='int64')  
x.astype('category')  
b=pd.api.types.CategoricalDtype(categories=[2,1],ordered=True)
x.astype(b)

col1    int64
col2    int64
dtype: object

0    1
1    2
dtype: category
Categories (2, int64): [2 < 1]

**DataFrame.count**

In [13]:
#count no.of non NA values 
#syn: DataFrame.count(axis=0, level=None, numeric_only=False) 
#level: int or str optional
import numpy as np
info = pd.DataFrame({"Person":["Parker", "Smith", "William", "John"], "Age": [27., 29, np.nan, 32] })
info.count()

Person    4
Age       3
dtype: int64

**DataFrame.cut**

In [14]:
#sort the data values into bins
#convert a continuous variable to a categorical variable
#syn:pandas.cut(x, bins, right=True, labels=None, retbins=False, precision=3, include_lowest=False, duplicates='raise')  
a=pd.DataFrame({'num':np.random.randint(1,50,10)})
print(a)
a['bins']=pd.cut(x=a['num'],bins=[1,23,50])
print(a)
print(a['bins'].unique())

   num
0   27
1   17
2   36
3   34
4   46
5   15
6   43
7   19
8   32
9   15
   num      bins
0   27  (23, 50]
1   17   (1, 23]
2   36  (23, 50]
3   34  (23, 50]
4   46  (23, 50]
5   15   (1, 23]
6   43  (23, 50]
7   19   (1, 23]
8   32  (23, 50]
9   15   (1, 23]
[(23, 50], (1, 23]]
Categories (2, interval[int64, right]): [(1, 23] < (23, 50]]

In [16]:
a=pd.DataFrame({'num':np.random.randint(1,50,10)})
print(a)
a['bins']=pd.cut(x=a['num'],bins=[1,23,50],labels=['low','high'])
print(a)
print(a['bins'].unique())

   num
0   10
1   24
2    4
3   11
4    5
5   10
6   25
7   36
8   49
9   44
   num  bins
0   10   low
1   24  high
2    4   low
3   11   low
4    5   low
5   10   low
6   25  high
7   36  high
8   49  high
9   44  high
['low', 'high']
Categories (2, object): ['low' < 'high']

[**DataFrame.describre**

In [17]:
#statistical data like percentile, mean and std
#syn:DataFrame.describe(percentiles=None, include=None, exclude=None)
a1 = pd.Series([1, 2, 3])  
a1.describe()

count    3.0
mean     2.0
std      1.0
min      1.0
25%      1.5
50%      2.0
75%      2.5
max      3.0
dtype: float64

In [18]:
a1 = pd.Series(['p', 'q', 'q', 'r'])  
a1.describe()

count     4
unique    3
top       q
freq      2
dtype: object

**DataFrame.drop_duplicates**

In [20]:
#common data cleaning task
#syn:DataFrame.drop_duplicates(subset=None, keep='first', inplace=False)  
#keep:consider duplicate values first:deletes other than 1st repeated value,last,False -deletes all
#inplace:boolean default False
emp = {"Name": ["Parker", "Smith", "William", "Parker"],"Age": [21, 32, 29, 21]} 
a=pd.DataFrame(emp)
print(a)
a=a.drop_duplicates()
print(a)

      Name  Age
0   Parker   21
1    Smith   32
2  William   29
3   Parker   21
      Name  Age
0   Parker   21
1    Smith   32
2  William   29

**Data Frame.groupby**

In [ ]:
#group data by at least one variables utilizing the groupby()
#syn:DataFrame.groupby(by=None, axis=0, level=None, as_index=True, sort=True, group_keys=True, squeeze=False, **kwargs)  
#level:axis is a MultiIndex (hierarchical), so, it will group by a particular level or levels


#group by operations
#splitting datasets
##obj.groupby('key')
##obj.groupby(['key1','key2'])
##obj.groupby(key,axis=1)
#analyzing data
#aggregating or combining data
#result of Groupby operation is not a DataFrame, but dict of DataFrame objects



#Aggregation: Computes summary statistic.
#Transformation: It performs some group-specific operation.
#Filtration: It filters the data by discarding it with some condition.